// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZN3CaWXlgvNiyF8mjEwca8C7nr-3rJhk',
    appId: '1:199991044917:web:fa2cbec3f906c9758a7a7c',
    messagingSenderId: '199991044917',
    projectId: 'news-map-today-6c241',
    authDomain: 'news-map-today-6c241.firebaseapp.com',
    storageBucket: 'news-map-today-6c241.firebasestorage.app',
    measurementId: 'G-50KFZMZ3MW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-zA7QrbNhc0l4OBWKy92Sho9bQkXfIA',
    appId: '1:199991044917:ios:256f5ee44b1b0a4d8a7a7c',
    messagingSenderId: '199991044917',
    projectId: 'news-map-today-6c241',
    storageBucket: 'news-map-today-6c241.firebasestorage.app',
    iosBundleId: 'com.Santiago.NewsMapMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM-zA7QrbNhc0l4OBWKy92Sho9bQkXfIA',
    appId: '1:199991044917:ios:af43f4f7c59aa1b58a7a7c',
    messagingSenderId: '199991044917',
    projectId: 'news-map-today-6c241',
    storageBucket: 'news-map-today-6c241.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
