name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # add these three:
  flutter_map: ^8.2.1
  latlong2:  ^0.9.1
  intl:      ^0.20.2

  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  firebase_auth: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
