name: news_map_mobile
description: A News Map Today app
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Mapping
  flutter_map: ^8.1.1
  latlong2:   ^0.9.0

  # Networking & Localization
  http: ^1.4.0
  intl: ^0.20.2

  # Secure storage for JWTs
  flutter_secure_storage: ^8.0.0

  # Environment variables (if you still need them)
  flutter_dotenv: ^5.0.2

  # State management (optional)
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
