name: news_map_mobile
description: A News Map Today app
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Mapping
  flutter_map: ^8.1.1
  latlong2:   ^0.9.0

  # Networking & Localization
  http: ^1.4.0
  intl: ^0.20.2

  # Firebase (updated)
  firebase_core:      ^3.15.2    # was ^3.15.1
  firebase_auth:      ^5.7.0     # was ^5.6.2
  firebase_analytics: ^11.6.0    # was ^11.5.2

  # Environment variables
  flutter_dotenv: ^5.0.2

  # Google sign‑in
  google_sign_in: ^7.1.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
